#!/bin/bash
# THIS SCRIPT IS TO DEMONSTRATE VARIABLE SCOPE AND HOW TO CALL ANOTHER SCRIPT AND PASS VARIABLES BETWEEN SCRIPTS
# GLOBAL VARIABLE

NAME=INDIA
echo "My Country: $NAME"
echo "PID of SCRITP-1: $$"
#sh 21-script-2.sh
source ./21-script-2.sh

# CALLING ANOTHER SCRIPT USING source COMMAND SO THAT THE VARIABLES DECLARED IN SCRIPT-1 ARE AVAILABLE IN SCRIPT-2
# IF WE USE sh OR bash COMMAND TO CALL ANOTHER SCRIPT, THE VARIABLES DECLARED IN SCRIPT-1 WILL NOT BE AVAILABLE IN SCRIPT-2 AS A NEW SUB SHELL WILL BE CREATED