#!/bin/bash
# THIS SCRIPT IS TO DEMONSTRATE VARIABLE SCOPE AND HOW TO CALL ANOTHER SCRIPT AND PASS VARIABLES BETWEEN SCRIPTS
# GLOBAL VARIABLE

echo "My Country: $NAME"
echo "PID of SCRITP-2: $$"

# ACCESSING THE GLOBAL VARIABLE DECLARED IN SCRIPT-1
# PRINTING THE VALUE OF THE VARIABLE DECLARED IN SCRIPT-1