#!/bin/bash

# EVERY THING INSIDE THE SHELL SCRIPT IS CONSIDER AS A STRING UNTIL YOU DECLARE IT AS A VARIABLE

NUMBER1=100
NUMBER2=200

SUM=$(($NUMBER1+$NUMBER2))

echo "SUM is : ${SUM}"

LEADERS=("Rahul" "Sachin" "Dhoni" "Kohli")

echo "All the leaders are : ${LEADERS[@]}"